services:
  movie_app:
    build:
      context: .
    ports:
      - "7001:7000"
    depends_on:
      - postgres_db
    command: sh -c " python manage.py runserver 0.0.0.0:7000"

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"