# Generated by Django 5.1.4 on 2025-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
